from enum import Enum


class ErrorCode(str, Enum):
    INVALID_COLUMNS = "INVALID_COLUMNS"
    EMPTY_FILE = "EMPTY_FILE"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    IMPORT_NOT_ALLOWED = "IMPORT_NOT_ALLOWED"
    BUSINESS_ERROR = "BUSINESS_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
